#!/usr/bin/env ruby

require 'fixed_gear'

site = FixedGear::Site.new(root: Dir.pwd)
argv = ARGV.dup
# p site: site
command = argv.shift
# p command: command, argv: argv

case command
when 'build'
  builder = FixedGear::Builder.new(site)
  builder.load_config
  builder.clean
  builder.call

when 'server'
  require 'fixed_gear'
  app = FixedGear::Server::Rack.for_site(site)
  Rack::Server.new(app: app, logger: FixedGear.logger).start { |server| @server = server }

when 'new'
  dir_name = argv.shift
  new_site = FixedGear::Site.new(root: site.root.join(dir_name).to_s)
  new_site.install

when 'update'
  site.update

when 'deploy'
  sync_bucket = -> profile, bucket {
    unless system("aws --profile #{profile} s3 --region eu-central-1 sync build/ \"s3://#{bucket}\" --acl public-read")
      warn "Install and configure aws-cli: brew install awscli; aws configure --profile #{profile}"
      exit 1
    end
  }
  raise "usage: fixed_gear deploy <PROFILE> <BUCKET>" if argv.size != 2
  builder = FixedGear::Builder.new(site)
  builder.clean
  builder.call
  sync_bucket[*argv]

else
  puts <<~USAGE
  FixedGear is a Sprockets based static site framework.

  Getting started:

    fixed_gear new DIR_NAME # sets up a new fixed_gear site in a folder named DIR_NAME

  Development:

    fixed_gear build  # builds the current site to build/
    fixed_gear server # starts a server from source/
    fixed_gear update # updates the config.ru file (for Rack servers)

  Deploy:

    fixed_gear deploy AWS_PROFILE_NAME BUCKET_NAME # deploys the site to AWS-S3
                                                   # (requires the aws CLI)

  USAGE
end
