#!/usr/bin/env ruby

require 'fixed_gear'

site = FixedGear::Site.new(root: Dir.pwd)
argv = ARGV.dup
p site: site
command = argv.shift
p command: command, argv: argv

case command
when 'build'
  builder = FixedGear::Builder.new(site)
  builder.clean
  builder.call

when 'server'
  require 'fixed_gear/server'
  FixedGear::Server.new(site).start

when 'new'
  new_root = argv.shift
  p new_root: new_root, exp: site.root.join(new_root).to_s
  new_site = FixedGear::Site.new(root: site.root.join(new_root).to_s)
  p new_site: new_site
  new_site.install

else
  usage
end
